### ISSUE TITLE
raspberry pi == boom

### ISSUE THREAD

**Issue by rflynn** [BAM-X/BigRedButton#2]
``` sh
pi@raspberrypi ~/src/BigRedButton $ source venv/bin/activate
(venv)pi@raspberrypi ~/src/BigRedButton $ sudo venv/bin/python buttonDriver.py
Traceback (most recent call last):
  File "buttonDriver.py", line 113, in <module>
    device_handle = get_device_handle()
  File "buttonDriver.py", line 42, in get_device_handle
    if dev.is_kernel_driver_active(interface) is True:
  File "/home/pi/src/BigRedButton/venv/local/lib/python2.7/site-packages/usb/core.py", line 992, in is_kernel_driver_active
    interface)
  File "/home/pi/src/BigRedButton/venv/local/lib/python2.7/site-packages/usb/backend/__init__.py", line 363, in is_kernel_driver_active
    _not_implemented(self.is_kernel_driver_active)
  File "/home/pi/src/BigRedButton/venv/local/lib/python2.7/site-packages/usb/backend/__init__.py", line 79, in _not_implemented
    raise NotImplementedError(func.__name__)
NotImplementedError: is_kernel_driver_active
Cleaning up
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "buttonDriver.py", line 86, in cleanup
    util.release_interface(device_handle, interface)
NameError: global name 'device_handle' is not defined
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "buttonDriver.py", line 86, in cleanup
    util.release_interface(device_handle, interface)
NameError: global name 'device_handle' is not defined
(venv)pi@raspberrypi ~/src/BigRedButton $ uname -a
Linux raspberrypi 3.12.32+ #721 PREEMPT Fri Nov 7 16:50:31 GMT 2014 armv6l GNU/Linux
(venv)pi@raspberrypi ~/src/BigRedButton $ 

```

**Comment by rflynn** [comment]
if i just wrap `is_kernel_driver_active` and catch the `NotImplementedError` i get:

``` sh
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] could not claim interface 0: Device or resource busy
Cleaning up
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "buttonDriver.py", line 92, in cleanup
    device_handle.attach_kernel_driver(interface)
  File "/home/pi/src/BigRedButton/venv/local/lib/python2.7/site-packages/usb/core.py", line 1017, in attach_kernel_driver
    interface)
  File "/home/pi/src/BigRedButton/venv/local/lib/python2.7/site-packages/usb/backend/__init__.py", line 376, in attach_kernel_driver
    _not_implemented(self.attach_kernel_driver)
  File "/home/pi/src/BigRedButton/venv/local/lib/python2.7/site-packages/usb/backend/__init__.py", line 79, in _not_implemented
    raise NotImplementedError(func.__name__)
NotImplementedError: attach_kernel_driver
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "buttonDriver.py", line 92, in cleanup
    device_handle.attach_kernel_driver(interface)
  File "/home/pi/src/BigRedButton/venv/local/lib/python2.7/site-packages/usb/core.py", line 1017, in attach_kernel_driver
    interface)
  File "/home/pi/src/BigRedButton/venv/local/lib/python2.7/site-packages/usb/backend/__init__.py", line 376, in attach_kernel_driver
    _not_implemented(self.attach_kernel_driver)
  File "/home/pi/src/BigRedButton/venv/local/lib/python2.7/site-packages/usb/backend/__init__.py", line 79, in _not_implemented
    raise NotImplementedError(func.__name__)
NotImplementedError: attach_kernel_driver
```
